Repository peteroin/feedaily, pull requests merged in 2025-10, with the labels that each got.

#28 fix(ui): Improved UI/UX of Landing Page and Authentication Section (Issue #21)
  frontend/src/components/LandingPage.css
  frontend/src/components/LandingPage.jsx
  frontend/src/pages/AdminLoginPage.jsx
  frontend/src/pages/RegisterPage.css
  frontend/src/pages/RegisterPage.jsx
Labels: enhancement, hacktoberfest, UI/UX

#34 fix: preserve user details in donation form
  frontend/src/pages/DashboardPage.jsx
Labels: bug, hacktoberfest, hacktoberfest-accepted

#44 fix(ui): Created AdminDeliveryRequestsPage.css for external CSS
  .gitignore
  frontend/package-lock.json
  frontend/src/pages/AdminDeliveryRequestsPage.css
  frontend/src/pages/AdminDeliveryRequestsPage.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#45 feat(auth): implement forgot password; show Logout/Get Started when logged-in; add Home button
  backend/server.js
  frontend/public/img/authBackground.png
  frontend/src/App.jsx
  frontend/src/components/DashboardLayout.jsx
  frontend/src/components/HomeButton.jsx
  frontend/src/components/LandingPage.jsx
  frontend/src/pages/AdminLoginPage.css
  frontend/src/pages/AdminLoginPage.jsx
  frontend/src/pages/ForgotPasswordPage.jsx
  frontend/src/pages/LoginPage.css
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/RegisterPage.css
  frontend/src/pages/RegisterPage.jsx
Labels: hacktoberfest, feature, hacktoberfest-accepted

#57 fix(encrypt): bcrypt in backend for password in admin, user login and register.
  backend/server.js
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#63 feat: Implement map modal for donation and route views
  frontend/src/components/MapModal.jsx
  frontend/src/pages/AdminDeliveryRequestsPage.jsx
  frontend/src/pages/DashboardPage.jsx
Labels: hacktoberfest, feature, hacktoberfest-accepted

#62 feat: dark/light toggle on landing page
  frontend/src/components/LandingPage.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
